apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudstack-management.fullname" . }}
  labels:
    {{- include "cloudstack-management.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "cloudstack-management.selectorLabels" . | nindent 4 }}
